services:
  - type: web
    name: riverdale-payroll
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        value: https://liuwhsumfxznzjyfhbfe.supabase.co
      - key: SUPABASE_KEY
        sync: false
